CREATE TABLE BRANDS(
     BRANDID INT CONSTRAINT PK_BRANDS_BRANDID PRIMARY KEY,
     BRANDNAME VARCHAR2(50));
     
INSERT INTO BRANDS VALUES(1,'AUDI');
INSERT INTO BRANDS VALUES(2,'BMW');
INSERT INTO BRANDS VALUES(3,'FORD');
INSERT INTO BRANDS VALUES(4,'HONDA');
INSERT INTO BRANDS VALUES(5,'TOYOTA');

CREATE TABLE CARS(
     CARID INT CONSTRAINT PK_CARS_CARID PRIMARY KEY,
     CARNAME VARCHAR2(50),
     BRANDID INT CONSTRAINT FK_CARS_BRANDID REFERENCES BRANDS NOT NULL);
     
INSERT INTO CARS VALUES(1,'AUDI R8 COUPE',1);
INSERT INTO CARS VALUES(2,'AUDI Q2',1);
INSERT INTO CARS VALUES(3,'AUDI S1',1);
INSERT INTO CARS VALUES(4,'BMW 2-SERIE CABRIO',2);
INSERT INTO CARS VALUES(5,'BMW i8',2);
INSERT INTO CARS VALUES(6,'FORD EDGE',3);
INSERT INTO CARS VALUES(7,'FORD MUSTANG FASTBACK',3);
INSERT INTO CARS VALUES(8,'HONDA S2000',4);
INSERT INTO CARS VALUES(9,'HONDA LEGEND',4);
INSERT INTO CARS VALUES(10,'TOYOTA GT86',5);
INSERT INTO CARS VALUES(11,'TOYOTA C-HR',5);


   
SELECT * FROM AUDI_CARS;



 CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ERPUSERPRAC"."AUDI_CARS" ("CARID", "CARNAME", "BRANDID") AS 
  SELECT CARID, CARNAME,BRANDID
   FROM CARS
   WHERE BRANDID = 1;
   
INSERT INTO AUDI_CARS VALUES(NULL,'BMW Z3 COUPE',2);

DROP VIEW AUDI_CARS;

CREATE VIEW VW_AUDI_CARS 
   AS
   SELECT CARID, CARNAME,BRANDID
   FROM CARS
   WHERE BRANDID = 1;
   
INSERT INTO VW_AUDI_CARS VALUES(12,'BMW Z3 COUPE',2);

SELECT * FROM CARS ;

UPDATE VW_AUDI_CARS
      SET
      CARNAME = 'BMW 1-SERIE COUPE',
      BRANDID = 2
      WHERE CARID = 3;

SELECT * FROM VW_FORD_CARS;

CREATE VIEW VW_FORD_CARS 
   AS
   SELECT CARID, CARNAME,BRANDID
   FROM CARS
   WHERE BRANDID = 3 WITH CHECK OPTION;
   
INSERT INTO VW_FORD_CARS VALUES(13,'AUDI RS6 AVANT',1

UPDATE VW_FORD_CARS
      SET
      CARNAME = 'HONDA NSX',
      BRANDID = 4
      WHERE CARID = 6;
      
      