CREATE VIEW VW_EMPLOYEE_YOS
     AS
    SELECT EMPLOYEE_ID, FIRST NAME ||' ' || LAST NAME AS FULL_NAME, 
           FLOOR(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) AS YOS
    FROM EMPLOYEE;
    
SELECT * FROM VW_EMPLOYEE_YOS
 WHERE YOS =15
 ORDER BY EMPLOYEE_ID;
 
 
 CREATE VIEW VW_CUSTOMER_CREDITS
     AS
     SELECT CID, NAME, CREDIT_LIMIT
     FROM CUSTOMERS WITH READ ONLY;

SELECT * FROM  VW_CUSTOMER_CREDITS; 

CREATE VIEW VW_BACKLOGS
   AS
   SELECT PRODUCT_NAME,
          EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
          SUM(QUANTITY*UNITPRICE) AMOUNT
    FROM ORDERS INNER JOIN ORDER_ITEMS USING (ORDER_ID)
                INNER JOIN PRODUCTS USING(PRODUCT_ID)
    WHERE STATUS = 'PENDING'
    GROUP BY EXTRACT(YEAR FROM ORDER_DATE), PRODUCT_NAME;
    