CREATE VIEW VW_SALESMAN
    AS
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME ,EMAIL, PHONE, HIRE_DATE, MANAGER_ID, JOB_TITLE
    FROM EMPLOYEEE
    WHERE JOB_TITLE = 'SALES REPRESENTATIVE';
    
SELECT * FROM VW_SALESMAN;

--########################################################
--CREATE ANOTHER VIEW FROM A VIEW
--########################################################

CREATE VIEW VW_SALESMAN_CONTACT 
    AS
    SELECT  FIRST_NAME, LAST_NAME ,EMAIL, PHONE
    FROM VW_SALESMAN;
    
SELECT * FROM VW_SALESMAN_CONTACT;

DROP VIEW VW_SALESMAN;

--########################################################
--CHECK STATUS OF THE VIEW 
--########################################################

SELECT
    OBJECT_NAME,
    STATUS
FROM
    USER_OBJECTS
WHERE
    OBJECT_TYPE = 'VIEW'
    AND OBJECT_NAME = 'VW_SALESMAN_CONTACTS';
    
DROP VIEW VW_SALESMAN_CONTACTS;